seed: 42

dataset: "cluster"
root_dir: "datasets"
project: 
# node_projection:
#   hidden_channels: 64
#   out_channels: 64
#   num_layers: 2
model:
  d_model: 48
  num_heads: 8
  dim_feedforward: 96
  dropout: 0.4
  num_layers: 16
  batch_norm: True
  abs_pe: "rw"
  abs_pe_dim: 3
  se: "gnn"
  gnn_type: "pna2"
  k_hop: 3
  in_embed: False
  use_global_pool: False
  gradient_gating_p: 0.0

batch_size: 32
epochs: 200
lr: 0.0005
weight_decay: 0.00001

logger:
  wandb_key: "43dac5c44e9d3eab9fd7f1a4d64e3f702eccf292" 
  project: cluster