seed: 42

dataset: "minesweeper"
root_dir: "datasets"

degree: True

node_projection:
  hidden_channels: 64
  num_layers: 3

model:
  d_model: 32
  num_heads: 1
  dim_feedforward: 64
  dropout: 0.5
  num_layers: 7
  batch_norm: True
  abs_pe: None
  abs_pe_dim: 0
  se: "gnn"
  gnn_type: "dirpna"
  k_hop: 5
  in_embed: True
  use_global_pool: False
  gradient_gating_p: 0
  jk: "lstm"
  alpha: 0.5
  learn_alpha: True

epochs: 1000
lr: 0.0005
weight_decay: 0.00001