seed: 42

dataset: "cluster"
root_dir: "datasets"

model:
  d_model: 48
  num_heads: 8
  dim_feedforward: 96
  dropout: 0.2
  num_layers: 6
  batch_norm: False
  abs_pe: "rw"
  abs_pe_dim: 3
  se: "gnn"
  gnn_type: "dirpna"
  k_hop: 3
  in_embed: False
  use_global_pool: False
  gradient_gating_p: 0.0

batch_size: 64
warmup: 5000
epochs: 200
lr: 0.0005
weight_decay: 0.0001

logger:
  project: "cluster_anisha"
  entity: "math_dl"
  wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8"