seed: 42

dataset: "zinc"
root_dir: "datasets/ZINC"

model:
  d_model: 64
  dim_feedforward: 128
  dropout: 0.3
  num_heads: 8
  num_layers: 6
  batch_norm: False
  abs_pe: "rw"
  abs_pe_dim: 20
  se: "gnn"
  gnn_type: "gcn"
  k_hop: 3
  use_edge_attr: True
  edge_dim: 32
  global_pool: "mean"
  gradient_gating_p: 0.0

lr: 0.001
weight_decay: 0.00001
warmup: 5000
batch_size: 128
epochs: 1