seed: 42

dataset: "pattern"
root_dir: "datasets"

model:
  d_model: 64
  num_heads: 8
  dim_feedforward: 128
  dropout: 0.2
  num_layers: 4
  batch_norm: True
  abs_pe: "rw"
  abs_pe_dim: 7
  se: "gnn"
  gnn_type: "dirgraphsage" # modified from defaut
  k_hop: 3
  in_embed: False
  use_global_pool: False
  gradient_gating_p: 0.0
  jk: null

batch_size: 32
epochs: 100
lr: 0.0003
weight_decay: 0.00001

logger:
  project: "pattern_anisha"
  entity: "math_dl"
  wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8"