seed: 42

dataset: "roman-empire"
root_dir: "datasets"

degree: False

model:
  d_model: 32
  num_heads: 1
  dim_feedforward: 64
  dropout: 0.5
  num_layers: 5
  batch_norm: False
  abs_pe: null
  abs_pe_dim: 0
  se: "gnn"
  gnn_type: "pna2"
  k_hop: 3
  in_embed: False
  use_global_pool: False
  gradient_gating_p: 0.0
  jk: null

epochs: 3000
lr: 0.0005
weight_decay: 0.00001