seed: 42

dataset: "roman-empire"
root_dir: "datasets"

degree: [True, False]

node_projection:
  hidden_channels: 64
  out_channels: 64
  num_layers: [2, 3]
model:
  d_model: 64
  num_heads: 8
  dim_feedforward: 128
  dropout: [0.3, 0.5, 0.7]
  num_layers: 1
  batch_norm: True
  abs_pe: "rw"
  abs_pe_dim: 32
  se: "gnn"
  gnn_type: "pna2"
  k_hop: [3, 6, 10]
  in_embed: True
  use_global_pool: False
  gradient_gating_p: [0.0, 1.0, 2.0]

epochs: 2000
lr: 0.001
weight_decay: 0.00001
wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8" 