seed: 42

dataset: "roman-empire"
root_dir: "datasets"

degree: False

model:
  d_model: 16
  num_heads: 1
  dim_feedforward: 32
  dropout: 0.5
  num_layers: 5
  batch_norm: False
  abs_pe: null
  abs_pe_dim: 0
  se: "gnn"
  gnn_type: "graphsage"
  k_hop: 3
  in_embed: False
  use_global_pool: False
  gradient_gating_p: 0.0

epochs: 10000
lr: 0.0005
weight_decay: 0
scheduler:
  step_size: 500
  gamma: 0.2

logger:
  project: "roman_empire_graphsage"
  entity: "math_dl"
  wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8" 