seed: 42

dataset: "roman-empire"
root_dir: "datasets"

degree: False

node_projection:
  hidden_channels: 16
  out_channels: 16
  num_layers: 2
model:
  d_model: 16
  num_heads: 1
  dim_feedforward: 32
  dropout: 0.5 # [0.3, 0.5, 0.7]
  num_layers: 1
  batch_norm: True
  abs_pe: None
  abs_pe_dim: 0
  se: "gnn"
  gnn_type: "graphsage"
  k_hop: 5 # [3, 8, 16]
  in_embed: True
  use_global_pool: False
  gradient_gating_p: 0.0 # [0.0, 1.0, 1.5]

epochs: 10
lr: 0.001
weight_decay: 0.00001

logger:
  project: "roman_empire_graphsage"
  entity: "math_dl"
  wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8" 