seed: 42

dataset: "roman-empire"
root_dir: "datasets"

degree: False

node_projection:
  hidden_channels: 64
  num_layers: 3
model:
  d_model: 32
  num_heads: 1
  dim_feedforward: 64
  dropout: 0.5
  num_layers: 5
  batch_norm: False
  abs_pe: null
  abs_pe_dim: 0
  se: "gnn"
  gnn_type: "pna2"
  k_hop: 8
  in_embed: True
  use_global_pool: False
  gradient_gating_p: 2.0
  jk: "lstm"

epochs: 3000
lr: 0.0005
weight_decay: 0.00001

logger:
  project: "roman_empire_pna2_dir"
  entity: "math_dl"
  wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8" 