seed: 42

dataset: "roman-empire"
root_dir: "datasets"

degree: False

model:
  d_model: [16, 32]
  num_heads: 1
  dim_feedforward: 32
  dropout: 0.5
  num_layers: 5
  batch_norm: False
  abs_pe: "rw"
  abs_pe_dim: 16
  se: "gnn"
  gnn_type: "graphsage"
  k_hop: 3
  in_embed: False
  use_global_pool: False
  gradient_gating_p: 0.0

epochs: 10000
lr: 0.0001
weight_decay: 0.00001
scheduler:
  step_size: 2000
  gamma: 0.8

logger:
  project: "roman_empire_graphsage"
  entity: "math_dl"
  wandb_key: "8f17d7bd011da005a1f4e9a75469497e3236f0b8" 